#!/usr/bin/env python3
"""Emit the camera and lens derivation as a standalone LaTeX note.

Every number in the PDF is computed here by importing camera_optics, so the
document cannot drift from the calculator the way the sizing chapter drifted
from the bill of materials.

    python tools/sizing-model/camera_optics_tex.py
    pdflatex -output-directory docs/sizing docs/sizing/camera-optics.tex
"""
from __future__ import annotations

import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from camera_optics import (ALTITUDES, AREA_HA, GROUNDSPEED, MODELLED,  # noqa: E402
                           N_DRONES, PERSON_M, SIDELAP, SPECIFIED,
                           at_altitude, blur_limit, optics)

BS = chr(92)
OUT = os.path.join(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))), "docs", "sizing",
    "camera-optics.tex")


def rows_for(c):
    out = []
    for h in ALTITUDES:
        a = at_altitude(c, h)
        out.append(f"{h:.0f} & {a['gsd_cm']:.2f} & {a['person_px']:.0f} & "
                   f"{a['swath_w']:.1f} $\\times$ {a['swath_h']:.1f} & "
                   f"{a['spacing']:.1f} & {a['n_lines']:d} & "
                   f"{a['sweep_s']:.0f} \\\\")
    return "\n".join(out)


so, mo = optics(SPECIFIED), optics(MODELLED)
s40, m40 = at_altitude(SPECIFIED, 40.0), at_altitude(MODELLED, 40.0)

cmp_rows = []
for name, a, b, unit in (
        ("Horizontal field of view", so["hfov"], mo["hfov"], "$^\\circ$"),
        ("Ground sample distance", s40["gsd_cm"], m40["gsd_cm"], "cm/px"),
        ("Survivor, long axis", s40["person_px"], m40["person_px"], "px"),
        ("Swath width", s40["swath_w"], m40["swath_w"], "m"),
        ("Line spacing", s40["spacing"], m40["spacing"], "m"),
        ("Transects per drone", s40["n_lines"], m40["n_lines"], ""),
        ("Sweep time per drone", s40["sweep_s"], m40["sweep_s"], "s")):
    d = (a - b) / b * 100 if b else 0.0
    cmp_rows.append(f"{name} & {a:.2f} & {b:.2f} & {d:+.1f}\\,\\% \\\\")
cmp_rows = "\n".join(cmp_rows)

blur_rows = "\n".join(
    f"{h:.0f} & {blur_limit(SPECIFIED, h, GROUNDSPEED)*1000:.2f} & "
    f"1/{1/blur_limit(SPECIFIED, h, GROUNDSPEED):.0f} \\\\"
    for h in ALTITUDES)

tile_rows = []
for ds, rate in ((1, 5.0), (2, 2.0)):
    w, h = SPECIFIED["px_w"] // ds, SPECIFIED["px_h"] // ds
    tiles = math.ceil(w / (640 * 0.8)) * math.ceil(h / (640 * 0.8))
    gsd = s40["gsd_cm"] * ds
    tile_rows.append(
        f"${ds}\\times$ & {w}$\\times${h} & {tiles} & {tiles*rate:.0f} & "
        f"{gsd:.2f} & {PERSON_M/(gsd/100):.0f} \\\\")
tile_rows = "\n".join(tile_rows)

DOC = rf"""% GENERATED by tools/sizing-model/camera_optics_tex.py -- do not edit.
\documentclass[10pt,a4paper]{{article}}
\usepackage[margin=18mm]{{geometry}}
\usepackage{{amsmath,booktabs,array,xcolor}}
\definecolor{{hi}}{{HTML}}{{0B5394}}
\definecolor{{dim}}{{HTML}}{{5A5A62}}
\definecolor{{warn}}{{HTML}}{{9C0006}}
\setlength{{\parindent}}{{0pt}}
\setlength{{\parskip}}{{4pt}}
\pagestyle{{empty}}
\renewcommand{{\arraystretch}}{{1.25}}

\begin{{document}}

{{\LARGE\bfseries Camera and lens: complete derivation}}\\[1mm]
{{\color{{dim}}Project RescueSwarm $\cdot$ NIDAR 2026--27 Track 1 $\cdot$
generated from \texttt{{tools/sizing-model/camera\_optics.py}}}}\\[1mm]
{{\color{{hi}}\rule{{\linewidth}}{{1pt}}}}

\section*{{1. The part, and a discrepancy}}

The bill of materials buys an \textbf{{Arducam IMX477}} with a 6\,mm S-mount
lens. Sony specifies the IMX477 as type 1/2.3: $4056\times3040$ at a
\textbf{{1.55\,\textmu m}} pixel pitch, 7.9\,mm diagonal.

\textcolor{{warn}}{{\textbf{{The sizing chapter was not written against that
sensor.}}}} \texttt{{sizing-calculations.md}}~\S8 states the baseline as
``1/1.8\,in, $4056\times3040$, $7.4\times5.6$\,mm, \textbf{{1.82\,\textmu m}}
pitch''. The pixel \emph{{count}} matches and the pixel \emph{{size}} does not.
Every optical quantity below scales with pitch, so none of the published
figures describe the camera being bought. Both cases are computed here.

\section*{{2. Sensor geometry}}

Active area follows from count and pitch:
\[
w = N_x\,p, \qquad h = N_y\,p, \qquad d = \sqrt{{w^2+h^2}}
\]
\[
w = 4056 \times 1.55\,\text{{\textmu m}} = {so['w_mm']:.3f}\,\text{{mm}},
\quad
h = 3040 \times 1.55\,\text{{\textmu m}} = {so['h_mm']:.3f}\,\text{{mm}},
\quad
d = {so['diag_mm']:.2f}\,\text{{mm}}
\]

\section*{{3. Field of view}}

The lens forms the image at its focal length, so each half-field is the
arctangent of half the sensor over $f$ --- exact, with no small-angle
approximation:
\[
\theta = 2\arctan\!\left(\frac{{s}}{{2f}}\right)
\]
\[
\text{{HFOV}} = 2\arctan\!\frac{{{so['w_mm']:.3f}}}{{12.0}}
= {so['hfov']:.1f}^\circ,
\qquad
\text{{VFOV}} = {so['vfov']:.1f}^\circ,
\qquad
\text{{DFOV}} = {so['dfov']:.1f}^\circ
\]
One pixel subtends {so['ifov_mdeg']:.2f}\,mdeg, which is the quantity that sets
the blur tolerance in~\S6.

\section*{{4. Ground sample distance and footprint}}

Sensor and ground form similar triangles about the lens, so
\[
\text{{GSD}} = \frac{{p\,H}}{{f}},
\qquad
W = 2H\tan\!\frac{{\text{{HFOV}}}}{{2}},
\qquad
S = W\,(1-\ell)
\]
for altitude $H$, pitch $p$, focal length $f$ and sidelap
$\ell = {SIDELAP*100:.0f}\,\%$.
Sidelap exists because attitude wobble, altitude error and lens distortion all
move the real footprint around; at zero sidelap a gap between passes is an
undetected survivor.

\begin{{center}}
\begin{{tabular}}{{r r r c r r r}}
\toprule
\textbf{{AGL}} & \textbf{{GSD}} & \textbf{{Survivor}} & \textbf{{Footprint}} &
\textbf{{Spacing}} & \textbf{{Lines}} & \textbf{{Sweep}} \\
(m) & (cm/px) & (px) & (m) & (m) & & (s) \\
\midrule
{rows_for(SPECIFIED)}
\bottomrule
\end{{tabular}}
\end{{center}}

Transect count and sweep time assume the {AREA_HA:.0f}\,ha area split
{N_DRONES} ways, each sub-region taken as square, flown at
{GROUNDSPEED:.0f}\,m/s with a 6\,s cost per turn.

\section*{{5. What the substitution changes, at 40\,m}}

\begin{{center}}
\begin{{tabular}}{{l r r r}}
\toprule
 & \textbf{{IMX477}} & \textbf{{Sizing model}} & \textbf{{Change}} \\
\midrule
{cmp_rows}
\bottomrule
\end{{tabular}}
\end{{center}}

A smaller pixel behind the same lens narrows the field and finens the ground
sample distance in the same proportion. \textbf{{Detection improves by
{(s40['person_px']/m40['person_px']-1)*100:.0f}\,\% and coverage costs
{(s40['sweep_s']/m40['sweep_s']-1)*100:.0f}\,\% more sweep time.}} Against 250
marks for detection and a 1800\,s mission budget, that trade favours the part
actually specified --- but it was never chosen, and the published figures
describe neither camera.

\section*{{6. Motion blur}}

Forward motion smears the image by $v\,t_{{\text{{exp}}}}$ on the ground. Holding
that under one pixel:
\[
t_{{\text{{exp}}}} \le \frac{{\text{{GSD}}}}{{v}}
\]

\begin{{center}}
\begin{{tabular}}{{r r r}}
\toprule
\textbf{{AGL}} (m) & \textbf{{Max exposure}} (ms) & \textbf{{Shutter}} \\
\midrule
{blur_rows}
\bottomrule
\end{{tabular}}
\end{{center}}

\texttt{{SYS-45}} already requires $\le 1/1000$\,s, which clears every altitude
with margin. Blur is not a binding constraint; it is Indian daylight driving
ISO down rather than exposure up.

\section*{{7. Tiling}}

A survivor occupies a few tens of pixels in a 12\,MP frame, so the detector is
fed overlapping crops rather than the whole image. Tile count depends on pixel
\emph{{count}}, so it is unaffected by the sensor substitution --- but the
\emph{{effective}} GSD after downsampling is not.

\begin{{center}}
\begin{{tabular}}{{c c r r r r}}
\toprule
\textbf{{Downsample}} & \textbf{{Frame}} & \textbf{{Tiles}} &
\textbf{{Inf./s}} & \textbf{{GSD}} (cm/px) & \textbf{{Survivor}} (px) \\
\midrule
{tile_rows}
\bottomrule
\end{{tabular}}
\end{{center}}

At $2\times$ downsampling and 2\,Hz the budget closes at 24 inferences per
second, unchanged. The survivor is
\textbf{{{PERSON_M/(s40['gsd_cm']*2/100):.0f}\,px}} in that downsampled frame
--- not the 47\,px the proposal currently states, which was computed at 60\,m on
the other sensor.

\section*{{8. What follows}}

Nothing here argues for changing the camera. The IMX477 is the better of the
two for detection, which is where the marks are. What it argues is that the
\emph{{documents}} should be re-baselined onto the part being bought: the GSD
table, the swath and line-spacing figures, the sweep times and the survivor
pixel count in the perception section. That work interacts with the unresolved
40\,m versus 60\,m survey-altitude question, because both move the same
quantities, and the two should be settled in one pass rather than two.

\vfill
{{\footnotesize\color{{dim}}Generated file. Regenerate with\\
\texttt{{python tools/sizing-model/camera\_optics\_tex.py}} then
\texttt{{pdflatex}}.\\
Every figure above is computed by
\texttt{{tools/sizing-model/camera\_optics.py}}.}}

\end{{document}}
"""

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(DOC)
print(f"wrote {os.path.relpath(OUT)}")
print(f"  IMX477   HFOV {so['hfov']:.1f} deg, GSD@40m {s40['gsd_cm']:.2f} cm/px, "
      f"survivor {s40['person_px']:.0f} px")
print(f"  modelled HFOV {mo['hfov']:.1f} deg, GSD@40m {m40['gsd_cm']:.2f} cm/px, "
      f"survivor {m40['person_px']:.0f} px")
