#!/usr/bin/env python3
r"""Export the sizing model to JSON so MATLAB can read it instead of repeating it.

THE PROBLEM THIS SOLVES. Figures, verification and simulation are moving to
MATLAB, and the obvious way to do that -- retype the design constants into .m
files -- creates a second source of truth. This repository has repeatedly found
that defect in itself: three different tile counts in one document, a mass line
naming a computer that was never bought, a fusion figure computed at an
abandoned altitude. Two authorities always diverge, and the divergence is
silent.

SO THE SPLIT IS: Python owns the PRIMITIVES. MATLAB re-derives from them and
asserts against the DERIVED values exported here. That is not duplication, it
is cross-validation -- two implementations, two languages, and a failing
assertion if they ever disagree.

Run:  python tools/sim/export_model.py
Emits: tools/sim/model.json
"""
from __future__ import annotations

import contextlib
import io
import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools", "sizing-model"))
with contextlib.redirect_stdout(io.StringIO()):
    import rescueswarm_sizing_model as M
    import camera_optics as CO

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "model.json")


def main() -> None:
    o = CO.optics(CO.SPECIFIED)
    a40 = CO.at_altitude(CO.SPECIFIED, 40.0)
    _, _, e_nom, e_rsw, e_lo = M.required_pack(M.MTOW)
    T, E, segs = M.mission(M.MTOW)

    doc = {
        "_README": "Generated by tools/sim/export_model.py. Do not hand-edit. "
                   "'primitives' are inputs; 'derived' are the model's own "
                   "results, which MATLAB re-derives and asserts against.",

        # ---- inputs the design chooses -----------------------------------
        "primitives": {
            "N_rot": M.N_rot, "D_m": M.D, "T_W": M.T_W,
            "g": M.g, "rho": M.rho, "rho_sl": M.rho_sl, "FM": M.FM,
            "eta_mot": M.eta_mot, "eta_esc": M.eta_esc,
            "P_avio_W": M.P_avio, "k_struct": M.k_struct,
            "spec_thrust_motor_N_per_kg": M.spec_thrust_motor,
            "k_esc": M.k_esc, "m_prop_ea_kg": M.m_prop_ea,
            "m_avio_kg": M.m_avio, "m_payload_sys_kg": M.m_payload_sys,
            "S_cells": M.S_cells, "P_par": M.P_par, "DOD": M.DOD,
            "V_nom": M.V_nom, "V_max": M.V_max, "V_min": M.V_min,
            "e_liion_Wh_per_kg": M.e_liion,
            "h_search_m": M.h_search, "v_search_ms": M.v_search,
            "px_w": CO.SPECIFIED["px_w"], "px_h": CO.SPECIFIED["px_h"],
            "pitch_um": CO.SPECIFIED["pitch_um"], "f_mm": CO.SPECIFIED["f_mm"],
            "water_target_m": 0.40,
            "coco_small_px2": CO.COCO_SMALL_PX2,
            "fusion_min_frames": CO.FUSION_MIN_FRAMES,
            "groundspeed_ms": CO.GROUNDSPEED,
            "kit_mass_kg": M.mp, "Cd": M.Cd, "A_tumb_m2": M.A_tumb,
            "motor_datasheet_cont_A": 26.5, "motor_datasheet_mass_g": 168.0,
        },

        # ---- what the model computes, for MATLAB to check itself against --
        "derived": {
            "MTOW_kg": M.MTOW, "fleet_kg": 3 * M.MTOW,
            "disk_area_m2": M.N_rot * math.pi * (M.D / 2) ** 2,
            "P_shaft_W": M.P_shaft, "P_hover_elec_W": M.Ph,
            "P_max_W": M.P_max,
            "I_hover_A": M.I_hov, "I_max_A": M.I_max,
            "I_pack_max_A": M.I_pack_max,
            "t_hover_min": M.t_hov,
            "E_pack_Wh": M.E_pack, "Ah_pack": M.Ah_pack,
            "m_pack_kg": M.m_pack, "n_cells": M.n_cells,
            "T_total_N": M.T_W * M.MTOW * M.g,
            "T_per_motor_kgf": M.T_W * M.MTOW / M.N_rot,
            "T_hover_per_motor_kgf": M.MTOW / M.N_rot,
            "mission_s": T, "mission_Wh": E,
            "E_nominal_Wh": e_nom, "E_resweep_Wh": e_rsw, "E_loiter_Wh": e_lo,
            "E_required_Wh": e_nom + e_rsw + e_lo,
            "E_usable_Wh": M.E_pack * M.DOD,
            "hfov_deg": o["hfov"], "vfov_deg": o["vfov"], "dfov_deg": o["dfov"],
            "sensor_w_mm": o["w_mm"], "sensor_h_mm": o["h_mm"],
            "gsd40_cm_per_px": a40["gsd_cm"],
            "swath_w_m": a40["swath_w"], "swath_h_m": a40["swath_h"],
            "looks_at_2Hz": CO.looks_per_target(CO.SPECIFIED, 40.0, 2.0)["frames"],
            "rate_for_12_looks_Hz": CO.rate_for_fusion(CO.SPECIFIED, 40.0),
        },

        # ---- mass statement, which must sum to MTOW ------------------------
        "mass_g": {k: v * 1000 for k, v in M.bd.items()},
        "payload_system_g": {k: v * 1000 for k, v in M.payload_system.items()},
        "avionics_g": {k: v * 1000 for k, v in M.avionics.items()},

        # ---- mission profile, for the dynamic simulations ------------------
        "mission_segments": [
            {"name": n, "duration_s": t, "power_W": p} for n, t, p in segs
        ],
    }

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(doc, fh, indent=1)

    n = len(doc["primitives"]) + len(doc["derived"])
    print(f"  wrote {os.path.relpath(OUT, ROOT)}")
    print(f"  {len(doc['primitives'])} primitives, {len(doc['derived'])} derived, "
          f"{len(doc['mission_segments'])} mission segments")
    print(f"  MATLAB re-derives the {len(doc['derived'])} derived values and asserts")


if __name__ == "__main__":
    main()
